### PR TITLE
[WiFi] Replace uptime counter with timestamp

### PR DESCRIPTION
**Pull request by xavier-contreras**
### Change Scope

This changes the leaf "uptime" under openconfig-ap-manager.yang from a uint32 counter to a new leaf of "up-time" which will be a timeticks64.  This is to make telemetry ingestion less churn heavy.  The intent of the leaf does not change.

This change is not backwards compatible as a leaf is replaced.

### Platform Implementations

oc-types:timeticks64 is used throughout other models and it should be trivial to implement.

### CODE REVIEW

**Comment by jsnyder81** [comment]
Should we move this to the new release model: https://github.com/openconfig/public/blob/master/doc/releases.md ?

If we follow this, would should aim to mark `uptime` as deprecated and introduce `up-time`.

**Comment by dplore** [comment]
> Should we move this to the new release model: https://github.com/openconfig/public/blob/master/doc/releases.md ?
> 
> If we follow this, would should aim to mark `uptime` as deprecated and introduce `up-time`.

Agreed, this is a good example where we can deprecate the leaf to make this change non-breaking.

**Comment by xavier-contreras** [comment]
> > Should we move this to the new release model: https://github.com/openconfig/public/blob/master/doc/releases.md ?
> > If we follow this, would should aim to mark `uptime` as deprecated and introduce `up-time`.
> 
> Agreed, this is a good example where we can deprecate the leaf to make this change non-breaking.

Fixed -- guidance did not exist prior to this PR, good to see it documented.  I also updated the version to minor increase since this is no longer a breaking change.

**Comment by jsnyder81** [comment]
LGTM

**Review by mike-albano — APPROVED** [review]
LGTM

**Pull request merged**
