### PR TITLE
Ntp auth types

### PR DESCRIPTION
**Pull request by awebsters**
### Change Scope

* Adding industry-standard cryptographic algorithms to NTP keys types.
* Backwards compatible -> YES

### CODE REVIEW

**Comment by awebsters** [comment]
@dplore

**Review by dplore — COMMENTED** [review]
Will review on Aug 27, OC operators meeting

**Comment by awebsters** [comment]
@dplore any update?

**Comment by dplore** [comment]
Reviewed in Sep 10, 2024 OC Operators meeting with no objections, thanks for the contribution!

**Review by dplore — APPROVED** [review]

**Pull request merged**
