### PR TITLE
openconfig/network-instances: Add counters under endpoint-peer and endpoint-vni

### PR DESCRIPTION
**Pull request by yini101**
Add counters container under the following **YANG Path** :

`- network-instances/network-instance/connection-points/connection-point/
endpoints/endpoint/vxlan/endpoint-peers/endpoint-peer/state/counters/`

`- network-instances/network-instance/connection-points/connection-point/
endpoints/endpoint/vxlan/endpoint-vnis/endpoint-vni/state/counters/`
`- network-instances/network-instance/connection-points/connection-point/
endpoints/endpoint/vxlan/endpoint-vnis/endpoint-vni/[ipv4|ipv6]/counters/`

### Generated YANG Tree
The counter container is added to existing YANG tree as shown below:
```
 +--rw vxlan
    +--rw config
    |  +--rw description?        string
    |  +--rw enabled?            boolean
    |  +--rw source-interface?   string
    +--ro state
    |  +--ro description?        string
    |  +--ro enabled?            boolean
    |  +--ro source-interface?   string
    +--ro endpoint-peers
    |  +--ro endpoint-peer* [peer-address]
    |     +--ro peer-address    -> ../state/peer-address
    |     +--ro state
    |     |  +--ro peer-address?         oc-inet:ip-address
    |     |  +--ro peer-state?           enumeration
    |     |  +--ro uptime?               oc-types:timeticks64
    |     |  +--ro control-plane-vnis*   oc-evpn-types:vni-id
    |     |  +--ro router-mac?           oc-yang:mac-address
    |     |  +--ro counters
    |     |     +--ro total-encap-pkts?           oc-yang:counter64
    |     |     +--ro total-encap-bytes?          oc-yang:counter64
    |     |     +--ro bum-encap-pkts?             oc-yang:counter64
    |     |     +--ro total-decap-pkts?           oc-yang:counter64
    |     |     +--ro total-decap-bytes?          oc-yang:counter64
    |     |     +--ro unicast-decap-pkts?         oc-yang:counter64
    |     |     +--ro bum-decap-pkts?             oc-yang:counter64
    |     |     +--ro bum-decap-multicast-pkts?   oc-yang:counter64
    |     |     +--ro bum-decap-ir-pkts?          oc-yang:counter64
    |     |     +--ro drop-decap-pkts?            oc-yang:counter64
    |     |     +--ro except-decap-pkts?          oc-yang:counter64
    +--ro endpoint-vnis
       +--ro endpoint-vni* [vni]
          +--ro vni      -> ../state/vni
          +--ro state
          |  +--ro vni?                        oc-evpn-types:evi-id
          |  +--ro multidestination-traffic?   union
          |  +--ro learning-mode?              oc-evpn-types:learning-mode
          |  +--ro vni-type?                   enumeration
          |  +--ro vni-state?                  enumeration
          |  +--ro svi-state?                  enumeration
          |  +--ro bridge-domain?              uint32
          |  +--ro l3-vrf-name?                string
          |  +--ro counters
          |     +--ro total-encap-pkts?           oc-yang:counter64
          |     +--ro total-encap-bytes?          oc-yang:counter64
          |     +--ro bum-encap-pkts?             oc-yang:counter64
          |     +--ro total-decap-pkts?           oc-yang:counter64
          |     +--ro total-decap-bytes?          oc-yang:counter64
          |     +--ro unicast-decap-pkts?         oc-yang:counter64
          |     +--ro bum-decap-pkts?             oc-yang:counter64
          |     +--ro bum-decap-multicast-pkts?   oc-yang:counter64
          |     +--ro bum-decap-ir-pkts?          oc-yang:counter64
          |     +--ro drop-decap-pkts?            oc-yang:counter64
          |     +--ro except-decap-pkts?          oc-yang:counter64
          +--ro ipv4
          |  +--ro state
          |     +--ro counters
          |        +--ro total-encap-pkts?           oc-yang:counter64
          |        +--ro total-encap-bytes?          oc-yang:counter64
          |        +--ro bum-encap-pkts?             oc-yang:counter64
          |        +--ro total-decap-pkts?           oc-yang:counter64
          |        +--ro total-decap-bytes?          oc-yang:counter64
          |        +--ro unicast-decap-pkts?         oc-yang:counter64
          |        +--ro bum-decap-pkts?             oc-yang:counter64
          |        +--ro bum-decap-multicast-pkts?   oc-yang:counter64
          |        +--ro bum-decap-ir-pkts?          oc-yang:counter64
          |        +--ro drop-decap-pkts?            oc-yang:counter64
          |        +--ro except-decap-pkts?          oc-yang:counter64
          +--ro ipv6
             +--ro state
                +--ro counters
                   +--ro total-encap-pkts?           oc-yang:counter64
                   +--ro total-encap-bytes?          oc-yang:counter64
                   +--ro bum-encap-pkts?             oc-yang:counter64
                   +--ro total-decap-pkts?           oc-yang:counter64
                   +--ro total-decap-bytes?          oc-yang:counter64
                   +--ro unicast-decap-pkts?         oc-yang:counter64
                   +--ro bum-decap-pkts?             oc-yang:counter64
                   +--ro bum-decap-multicast-pkts?   oc-yang:counter64
                   +--ro bum-decap-ir-pkts?          oc-yang:counter64
                   +--ro drop-decap-pkts?            oc-yang:counter64
                   +--ro except-decap-pkts?          oc-yang:counter64  
```

The model change above is backwards compatible.

### Platform Implementations

Arista Implementation: [public documentation](https://www.arista.com/en/um-eos/eos-vxlan-commands#xx1152704)
**Output:**
```

switch> show vxlan counters vtep
                                                                   Decap Drop or
                                  Decap Known           Decap BUM      Exception
VTEP         Decap Bytes      Unicast Packets           Packets          Packets
-------- --------------- -------------------- -------------------- -------------
1.0.14.1     62526968000            312632701            312636979             2
1.0.16.1             800                    2                    6     312279633
1.0.23.1             800                    2                    6             2
unlearnt               0                    0                    0             0
                                              Encap Drop or
                                                  Exception
VTEP         Encap Bytes        Encap Packets       Packets
-------- --------------- -------------------- -------------
1.0.14.1     30579308814            268239551             2
1.0.16.1            1140                   10             2
1.0.23.1               0                    0             0
```

### CODE REVIEW

**Comment by dplore** [comment]
Here are a few relevant references for vxlan tunnel counters:

- [Nokia SRLinux](https://documentation.nokia.com/srlinux/23-3/books/data-model-reference/srl_nokia-tunnel_0.html#yc7392__l7309)
- [NVidia Onyx](https://docs.nvidia.com/networking/display/onyxv3102002/vxlan+commands)
- [Cisco NXOS](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/7-x/vxlan/configuration/guide/b_Cisco_Nexus_9000_Series_NX-OS_VXLAN_Configuration_Guide_7x/b_Cisco_Nexus_9000_Series_NX-OS_VXLAN_Configuration_Guide_7x_chapter_011.html) 
  - example 
      - `show nve peers <peer_IP_address> interface <interface_ID> counters`

**Comment by dplore** [comment]
Will review on Jan 9, 2023 OC Operators meeting

**Review by dplore — DISMISSED** [review]
LGTM and reviewed at Jan 9, 2024 OC operators meeting.   We would appreciate any other comments from vendors on their support for these counters.

**Comment by dplore** [comment]
Set for last call on Jan 23, 2024.

**Comment by mikewiebe** [comment]
We did an analysis of this model and have the following comments and questions.

**Comments:**
* We should probably have properties to support both encap and decap for bum traffic
* Some platforms support counters that are both per/peer and per/vni
    * It would be good to create a shared container that could be referenced from both `endpoint-peers` and `endpoint-vnis`
    * Additionally per/vni counters could be either IPv4 or IPv6.  The model should account for this.
* The model should also support software forwarded packets (working on getting sample output / reference)

**Questions:** 
* For total encap/decap packets, does this refer to (unicast + bum traffic)?
* Does it make sense to breakout the `bum-decap-pkts` into ingress-replication and multicast?

**Comment by rolandphung** [comment]
@mikewiebe The latest changes should have addressed most of your concerns.

As for software forwarded packets, this might be a larger task and out of the scope of this PR. I would suggest this be tackled separately.

**Comment by dplore** [comment]
@yini101 please merge with the latest master branch.  This should fix the pyangbind check which is failing.

**Comment by dplore** [comment]
@mikewiebe I reset the last call date to Feb 14th, 2024.  We would love to have your review on the latest changes.

**Comment by mikewiebe** [comment]
> @mikewiebe I reset the last call date to Feb 14th, 2024. We would love to have your review on the latest changes.

We took a look at the latest changes and have the following comments

* We don't think it makes sense to have `ipv4` and `ipv6` containers under `endpoint-peers`.  The `peer-address` is the key and will already represent the `ipv4` or `ipv6` peer.
* The `ipv4` and `ipv6` containers under `endpoint-vnis` make sense but we think that any data should be strictly related to the functionality under that container - if we are under vxlan we should care only about vxlan encapsulation and not about inner traffic type- so only vxlan (or vni) counters should be there.

**Comment by yini101** [comment]
@mikewiebe 
Hello, thanks for the review. We’ve updated the PR with the following changes:
1. Remove per address family counter container under endpoint-peers because the peer-address implicitly indicates the address family.
2. Keep per address family counter container under endpoint-vnis as it is.

**Review by pbrisset — APPROVED** [review]

**Review by mikewiebe — APPROVED** [review]

**Review by dplore — APPROVED** [review]

**Pull request merged**
