### PR TITLE
Add prefix qualifiers to `network-instance-ref`.

### PR DESCRIPTION
**Pull request by robshakir**
```
 * (M) release/models/network-instance/openconfig-network-instance.yang
 * (M) release/models/network-instance/openconfig-network-instance-l2.yang
   - Add prefixes to network-instance-ref typedef.
```

Checking against CI to address #184.

### CODE REVIEW

**Comment by earies** [comment]
Looks like we need an approval here still before merge - this LGTM - @robshakir @dplore - PTAL thx

**Comment by dplore** [comment]
Hi @earies, can you resolve the merge conflict?

**Comment by earies** [comment]
@dplore @robshakir - Just noticed this is still pending - can we get this resolved/merged?  Thx

**Comment by robshakir** [comment]
Done, re-running the CI here.

It's not entirely clear to me that this is required though.

RFC6020 says:

> [5.4](https://datatracker.ietf.org/doc/html/rfc6020#section-5.4).  Resolving Grouping, Type, and Identity Names
>
>   Grouping, type, and identity names are resolved in the context in
>   which they are defined, rather than the context in which they are
>   used.

Given that this is the case, then the `typedef` here is defined in the context of `openconfig-network-instance` that does not need this prefixing, such that I don't think toolchains that require it are fully implementing this correctly.

**Comment by earies** [comment]
> Done, re-running the CI here.
> 
> It's not entirely clear to me that this is required though.
> 
> RFC6020 says:
> 
> > [5.4](https://datatracker.ietf.org/doc/html/rfc6020#section-5.4).  Resolving Grouping, Type, and Identity Names
> > Grouping, type, and identity names are resolved in the context in
> > which they are defined, rather than the context in which they are
> > used.
> 
> Given that this is the case, then the `typedef` here is defined in the context of `openconfig-network-instance` that does not need this prefixing, such that I don't think toolchains that require it are fully implementing this correctly.

Thx @robshakir and yes per that section in both 1.0 and 1.1 spec, I am also leaning to this being a common toolchain resolver issue now that likely needs to be dug into further.

**Comment by robshakir** [comment]
@earies thanks! I was just wondering whether we should just add a `TODO` and submit this.

It seems to me that if an implementation does implement the above logic, then `oc-netinst` is alwayhs resolved in the context of `openconfig-network-instance`. To this end, it should be harmless to have this be included.

The thing that I am not sure is whether implementations are robust to this -- e.g., if I do:

```yang
module a {
  prefix "a";
  typedef a-ref {
    type leafref { path "/a:a"; }
  }
  leaf-list a { type string; }
}
```

and then

```yang
module b {
   prefix b;
   import a { prefix not-a; }
   leaf q { type not-a:a-ref; }
}
```

then in this case, an implementation that interprets `a-ref` in the context of `a` will work, but one that uses the context of `b` will not work correctly.

ygot/goyang appear to support this case fine, but I'm not sure about all toolchains.

**Comment by robshakir** [comment]
Which major toolchain is it that doesn't work with the current setup?

**Comment by earies** [comment]
> Which major toolchain is it that doesn't work with the current setup?

So far you can observe this behavior in `libyang` (yanglint 2.0.221) and `yangson` (1.4.13)

```
module a {
  yang-version "1";
  namespace "urn:a";
  prefix a;

  typedef instance-ref {
    type leafref {
      path "/a/b/name";
    }
  }

  container a {
    list b {
      key name;
      leaf name { type string; }
    }
  }
}
```
```
module c {
  yang-version "1";
  namespace "urn:c";
  prefix c;

  import a {
    prefix a;
  }

  container c {
    leaf instance {
      type a:instance-ref;
    }
  }
}
```

```
{
    "a:a": {
        "b": [
            {
                "name": "TEST1"
            }
        ]
    },
    "c:c": {
        "instance": "TEST1"
    }
}
```

yangson:
```
yangson.exceptions.InvalidLeafrefPath: c:instance
```

libyang:
```
libyang err : Not found node "a" in path. (Schema location "/c:c/instance".)
```

**Comment by robshakir** [comment]
Ah, the fix was reverted in libyang. There was a discussion [here](https://github.com/CESNET/libyang/issues/1082). My interpretation is not necessarily the same here, but as with the wonderful nature of rfc6020 or rfc7950 there seem to be many places where different interpretations are possible.

Given that this doesn't, to our CI's knowledge, break tooling that we run CI against, and should fix libyang+yangson -- I suggest we submit it. WDYT?

**Comment by earies** [comment]
> Ah, the fix was reverted in libyang. There was a discussion [here](https://github.com/CESNET/libyang/issues/1082). My interpretation is not necessarily the same here, but as with the wonderful nature of rfc6020 or rfc7950 there seem to be many places where different interpretations are possible.
> 
> Given that this doesn't, to our CI's knowledge, break tooling that we run CI against, and should fix libyang+yangson -- I suggest we submit it. WDYT?

Agreed on clarifying and fixing the interpretation in consistent fashion across toolchains as well as merging this patch set for now.

This has been done a handful of times already throughout the model sets:
* https://github.com/openconfig/public/pull/598
* https://github.com/openconfig/public/pull/611

**Comment by robshakir** [comment]
Sold and merged, thanks for the review @earies!

**Pull request merged**
