### PR TITLE
Add transition OPMODES to wifi-phy models

### PR DESCRIPTION
**Pull request by jsnyder81**
### Change Scope

* [Please briefly describe the change that is being made to the models.]
Adding transition OPMODES to the wifi-phy models so there is less ambiguity to what the vendors default to.

* [Please indicate whether this change is backwards compatible.]
This change is an addition only, should be non-breaking.
### Platform Implementations

 * Implementation A: [Aruba WPA3 Configuration Guide](https://www.arubanetworks.com/techdocs/ArubaOS_87_Web_Help/Content/arubaos-solutions/802-1x/wpa3-supp.htm) 
 * Implementation B: [Cisco WPA3 Configuration](https://www.cisco.com/c/en/us/td/docs/wireless/controller/9800/16-12/config-guide/b_wl_16_12_cg/wpa3.html) and/or
   implementation output.

Currently both Arista and Aruba support most of these options today.

### CODE REVIEW

**Review by xavier-contreras — APPROVED** [review]
LGTM

**Comment by dplore** [comment]
@jsnyder81

**Review by mike-albano — APPROVED** [review]
LGTM

**Comment by dplore** [comment]
@jsnyder81 some CI checks are failing here.  if you would like to pursue this pr, please fix and we can approve

**Comment by jsnyder81** [comment]
@dplore Yeah... hung up on some other projects.  will try to get this done soon.

**Pull request merged**
