### PR TITLE
Route dest policy

### PR DESCRIPTION
**Pull request by awebsters**
[Note: Please fill out the following template for your pull request. lines
tagged with "Note" can be removed from the template.]

Add policy match conditions internal, external, and both to IS-IS

### Change Scope

* Additional feature to IS-IS policy allowing filtering by a routes destination type
* Change is backward compatible

### CODE REVIEW

**Comment by dplore** [comment]
Hi, please sign the CLA and provide at least 2 references to implementations of this feature.  This is needed before the change will be reviewed.  Thanks

**Comment by awebsters** [comment]
> Hi, please sign the CLA and provide at least 2 references to implementations of this feature. This is needed before the change will be reviewed. Thanks

Given the simplicity of the change, is 2 references actually necessary? We could provide a sample code implementation to further cement the need for the change.

**Comment by dplore** [comment]
> > Hi, please sign the CLA and provide at least 2 references to implementations of this feature. This is needed before the change will be reviewed. Thanks
> 
> Given the simplicity of the change, is 2 references actually necessary? We could provide a sample code implementation to further cement the need for the change.

2 references are the minimum and more are preferred.  This helps validate vendor neutrality of the configuration method and feature behavior.   Is there an issue with providing references?      

Occasionally new features are defined in OpenConfig ahead of implementations, but it is discouraged. See the [contribution guide](https://github.com/openconfig/public/blob/master/doc/contributions-guide.md).

**Comment by chrisy** [comment]
> Given the simplicity of the change, is 2 references actually necessary? We could provide a sample code implementation to further cement the need for the change.

Adding on to @dplore's response, by "references" we simply mean links to documentation or examples of the implementation. It's really a very low bar! What we're looking to avoid is replicating vendor-specific structures in OpenConfig since that adds little value and can cause modeling issues later if another vendor does pop up, so our approach is to ask for these pointers to how a mix of vendors implement a feature -- even if it seems obvious, because documentation is always good.

**Comment by awebsters** [comment]
Closed in favour of new PR https://github.com/openconfig/public/pull/863

**Pull request closed without merging**
