### PR TITLE
Add SR-TE policy counter for Egress packets.

### PR DESCRIPTION
**Pull request by romiarista**
Add 2 containers 
1. policy-counters - Egress packet counter for SR-TE policy.
2. segment-list-counters - Egress packet counter for segment-list belonging to SR-TE policy.

### CODE REVIEW

**Comment by romiarista** [comment]
signed CLA.

**Comment by romiarista** [comment]
I signed it!

**Comment by romiarista** [comment]
I signed it!

**Comment by romiarista** [comment]
I signed it!

**Comment by romiarista** [comment]
@googlebot I signed it!

**Comment by romiarista** [comment]
I signed it!

**Comment by romiarista** [comment]
@googlebot I signed it!

**Comment by romiarista** [comment]
@googlebot I signed it!)

**Comment by romiarista** [comment]
@googlebot I signed it! )

**Comment by romiarista** [comment]
@googlebot I signed it! )

**Comment by romiarista** [comment]
@googlebot I signed it!)

**Comment by romiarista** [comment]
@googlebot I signed it

**Comment by romiarista** [comment]
@googlebot I signed it!

**Comment by romiarista** [comment]
@googlebot I signed it! )

**Comment by robshakir** [comment]
@vcheny -- PTAL at this proposed change which I believe addresses some of things that we discussed w.r.t the SR-TE policy model.

**Comment by vcheny** [comment]
Policy ingress/egress counters are modeled here.
https://github.com/openconfig/public/blob/master/release/models/segment-routing/openconfig-srte-policy.yang#L211

**Pull request closed without merging**
