### PR TITLE
Update openconfig-if-ethernet.yang

### PR DESCRIPTION
**Pull request by Prasanth-KV**
Added speeds - 200GB and 400GB
Industry supports these speeds now.

### CODE REVIEW

**Comment by Prasanth-KV** [comment]
@googlebot I signed it!

**Comment by Prasanth-KV** [comment]
@googlebot I signed it!

**Comment by robshakir** [comment]
Thanks for this change, I'm merging it upstream. Apologies for the delay in responding!

r.

**Comment by robshakir** [comment]
Thanks for this change, it was merged in c1a40f5f7671f92e882c3fa8e75a30dd9ef08726.

**Pull request closed without merging**
