### PR TITLE
Fix typo in openconfig_style_guide.md

### PR DESCRIPTION
**Pull request by ludamad**

### CODE REVIEW

**Comment by ludamad** [comment]
@googlebot I signed it!

**Comment by aashaikh** [comment]
Thanks for catching this.

**Comment by ludamad** [comment]
Hi @aashaikh can you let me know why you declined to merge the PR? As far as I see, the typo still exists

**Comment by aashaikh** [comment]
We've incorporated your change (with attribution) in the private repo -- it will be published along with other changes shortly.  (see the annotation above regarding the merged PR#736).  Thanks again.

**Pull request closed without merging**
