### PR TITLE
ISIS LDP Sync restructuring

### PR DESCRIPTION
**Pull request by exa-arrcus**
- Move ISIS/MPLS config to separate grouping
- Reuse grouping under isis interfaces

### CODE REVIEW

**Comment by exa-arrcus** [comment]
The main goal for this PR is to introduce support for LDP sync at the interface level as various implementations support.  In doing so requires to break apart these containers into reuseable groupings

The global tree remains as-is
```
module: openconfig-network-instance
  +--rw network-instances
     +--rw network-instance* [name]
        +--rw protocols
           +--rw protocol* [identifier name]
              +--rw isis
                 +--rw global
                    +--rw mpls
                       +--rw igp-ldp-sync
                          +--rw config
                          |  +--rw enabled?                 boolean
                          |  +--rw post-session-up-delay?   uint16
                          +--ro state
                             +--ro enabled?                 boolean
                             +--ro post-session-up-delay?   uint16
```

Introduction of the `mpls` tree at the interface level
```
module: openconfig-network-instance
  +--rw network-instances
     +--rw network-instance* [name]
        +--rw protocols
           +--rw protocol* [identifier name]
              +--rw isis
                 +--rw interfaces
                    +--rw interface* [interface-id]
                       +--rw mpls
                          +--rw igp-ldp-sync
                             +--rw config
                             |  +--rw enabled?                 boolean
                             |  +--rw post-session-up-delay?   uint16
                             +--ro state
                                +--ro enabled?                 boolean
                                +--ro post-session-up-delay?   uint16
```

**Comment by robshakir** [comment]
Hi @exa-arrcus,

This LGTM. Just to document the research that I did here:

- Supported in XR ([docs](https://www.cisco.com/c/en/us/td/docs/ios_xr_sw/iosxr_r3-7/mpls/configuration/guide/gc37ldp.html#wp1166228))
- Supported in JUNOS ([docs](https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/ldp-synchronization-edit-protocols-isis.html))

I assume it's also supported in Arrcus based on your change, so this looks good to take upstream.

Thanks!
r.

**Comment by exa-arrcus** [comment]
Thx @robshakir - yes, we support the global schema above and per-interface `enabled` node (`post-session-up-delay` supported globally only)

**Comment by robshakir** [comment]
Thanks for this contribution, it was merged in 925eeb2e7e7bf21bfa0fd18c0f2ad128f5c31f50.

**Pull request closed without merging**
