### PR TITLE
Add ETH_400GBASE_PSM4 PMD type to openconfig-transport-types

### PR DESCRIPTION
**Pull request by atmanmehta**
[Note: Before this PR can be reviewed please agree to the CLA covering this
repo. Please also review the contribution guide -
https://github.com/openconfig/public/blob/master/doc/external-contributions-guide.md]

### Change Scope

* Add ETH_400GBASE_PSM4 PMD type to openconfig-transport-types.
* This change is backward compatible.
### Platform Implementations

Adding this since it is already an industry standard.

### CODE REVIEW

**Comment by dplore** [comment]
@ejbrever can you review this one for us?

**Comment by ejbrever** [comment]
In discussing with a @thofmeister it sounds like this 400G PSM4 is really DR4 which we already have here:
https://github.com/openconfig/public/blob/master/release/models/optical-transport/openconfig-transport-types.yang#L1042

Is there a reason that wouldn't work? Thanks.

**Comment by atmanmehta** [comment]
Based on discussions with @ejbrever and @thofmeister, changed the type to ETH_400GMSA_PSM4. PTAL.

**Comment by ejbrever** [comment]
I'm good with this, but as I'm not nearly as close to optics as tad@, I'll leave the final LGTM to him.

**Comment by thofmeister** [comment]
ETH_400GMSA_PSM4 LGTM.

Thanks,
Tad

**Review by ejbrever — APPROVED** [review]
LGTM

**Review by dplore — APPROVED** [review]

**Pull request merged**
