### PR TITLE
Support PTP Yang model based on IEEE standard

### PR DESCRIPTION
**Pull request by sallylsy**
### Change Scope

Original PR: https://github.com/openconfig/public/pull/1036

This model is based on [ieee1588-ptp-ms.yang](https://github.com/YangModels/yang/blob/287f9e307c3b04282c6de1e75ab8afea6225f11a/standard/ieee/draft/1588/ieee1588-ptp-ms.yang)

Operational and configurational data are added based on the definition of IEEE standard.

### CODE REVIEW

**Comment by RodneyCummings** [comment]
FYI: The official YANG modules for IEEE Std 1588e-2024 are now available at:
https://github.com/YangModels/yang/tree/main/standard/ieee/published/1588

The only change from the draft P1588e module used for this PR is change of "1588e-XXXX" to "1588e-2024" in the initial description (no changes to nodes).

**Comment by proberts2022** [comment]
There now seems to be Issue #1039 , Pull request #1036 and this new Pull Request #1103 
Please advise on where we are to add comments

**Comment by RodneyCummings** [comment]
Hi Peter,

I'm adding Doug for feedback on management of unicast and mixed unicast/multicast. 1588-2019 has data sets (i.e., info model) for unicast, and the YANG in 1588e modeled those data sets 1-1, and OpenConfig's YANG was in turn based on that 1588e YANG (as I understand). Doug was involved in the 1588-2019 data sets for unicast. I wasn't directly involved there.

Doug: My impression is that the OpenConfig YANG for 1588 is adding more data sets members for unicast. We might want to reflect that over to 1588 someday.

Rodney

**Comment by dplore** [comment]
@sallylsy would you like to move this forward?

**Comment by sallylsy** [comment]
Yes, sorry for the late reply.

unicast-multicast
The default-ds level indicates how we get the clock. And the port-ds level indicates how we send the clock down the stream - using unicast or multicast

default-ds:config:udp6-scope.
We inherited this leaf from SONIC. https://github.com/project-arlo/sonic-mgmt-framework/blob/562cd84ff3fec9ca705c7df621742f2daa61ce71/models/yang/sonic/sonic-ptp.yang#L477
Thanks for the explanation. From the description in SONIC, this will be used as the second byte of the primary address. My understanding is, this would be apply to all the IPv6 under the clock instance. We do not have an use case now, my suggestion would be 1. we leave this leaf at the current level, or 2. we drop this leaf from the model for now

master-ip
I double checked the IPs populated for this field. This is a list of host ip and associated with the design between ToR and host. The field may not apply generically, I would drop this leaf.

**Comment by sallylsy** [comment]
I reconsidered udp6-scope. This is defined in SONIC yang model. We did not find a strong motivation from IEEE or use case for this leaf existing in OC model. Dropped this leaf

**Comment by sallylsy** [comment]
IEEE copyright information is updated in the description

**Comment by sallylsy** [comment]
Hi @dplore , I fixed the revision and lint errors.

**Review by dplore — APPROVED** [review]

**Pull request closed without merging**
