### PR TITLE
clarification in description of last-prefix-limit-exceeded

### PR DESCRIPTION
**Pull request by rszarecki**

### CODE REVIEW

**Review by rolandphung — APPROVED** [review]

**Comment by s19nal** [comment]
discussed on weekly operators meeting - looks good to merge

**Comment by dplore** [comment]
@rszarecki looks good to me too, but need to fix the version numbering:

```
submodule versions must match the belonging module's version

module set openconfig-bgp is at 9.7.1 (openconfig-bgp-neighbor.yang), non-matching files: openconfig-bgp-common-multiprotocol.yang (9.7.0), openconfig-bgp-common-structure.yang (9.7.0), openconfig-bgp-common.yang (9.7.0), openconfig-bgp-global.yang (9.7.0), openconfig-bgp-peer-group.yang (9.7.0), openconfig-bgp.yang (9.7.0)
```

**Pull request merged**
