### PR TITLE
Correct ROUTER_INFORMATION_LSA to ROUTER_INFORMATION.

### PR DESCRIPTION
**Pull request by nkitchen**
* (M) release/models/ospf/openconfig-ospfv2-lsdb.yang

  #237

### CODE REVIEW

**Comment by dplore** [comment]
Need to fix the CI checks (version and date updates) but otherwise, LGTM:

**Review by dplore — CHANGES_REQUESTED** [review]
Please fix the version numbers/dates, then we can merge this fix.

**Comment by nkitchen** [comment]
> Please fix the version numbers/dates, then we can merge this fix.

What change should I make to the version number, instead of bumping it to 0.5.2?

**Comment by dplore** [comment]
> > Please fix the version numbers/dates, then we can merge this fix.
> 
> What change should I make to the version number, instead of bumping it to 0.5.2?

Sorry for the confusion, v0.5.2 is a good value, but there are submodules that also need to be synchronized / bumped.  The [miscellaneous check](https://gist.github.com/OpenConfigBot/f800aa99852d1055aca4ddec9dcff60f) has the details:

⛔  submodule versions must match the belonging module's version
module set openconfig-ospfv2 is at 0.5.2 (openconfig-ospfv2-lsdb.yang), non-matching files: openconfig-ospfv2-area-interface.yang (0.5.1), openconfig-ospfv2-area.yang (0.5.1), openconfig-ospfv2-common.yang (0.5.1), openconfig-ospfv2-global.yang (0.5.1), openconfig-ospfv2.yang (0.5.1)

**Review by dplore — APPROVED** [review]

**Pull request merged**
