### PR TITLE
Publish PTP Yang model

### PR DESCRIPTION
**Pull request by sallylsy**
### Change Scope

* Support PTP (Precision Time Protocol) in OpenConfig. PTP model implementation is based on IEEE1588
* This change is backwards compatible

### Model

```
module: openconfig-ptp
  +--rw ptp
     +--rw instances
     |  +--rw instance* [id]
     |     +--rw id                 -> ../config/id
     |     +--rw config
     |     |  +--rw id?   uint32
     |     +--ro state
     |     |  +--ro id?                        uint32
     |     |  +--ro current-dataset-state
     |     |  |  +--ro steps-removed?        uint16
     |     |  |  +--ro offset-from-master?   oc-ptp-types:time-interval-type
     |     |  |  +--ro mean-path-delay?      oc-ptp-types:time-interval-type
     |     |  +--ro time-properties-dataset
     |     |     +--ro current-utc-offset-valid?   boolean
     |     |     +--ro current-utc-offset?         int16
     |     |     +--ro leap59?                     boolean
     |     |     +--ro leap61?                     boolean
     |     |     +--ro time-traceable?             boolean
     |     |     +--ro frequency-traceable?        boolean
     |     |     +--ro ptp-timescale?              boolean
     |     |     +--ro time-source?                uint8
     |     +--rw default-dataset
     |     |  +--rw config
     |     |  |  +--rw priority1?           uint8
     |     |  |  +--rw priority2?           uint8
     |     |  |  +--rw domain-number?       uint8
     |     |  |  +--rw slave-only?          boolean
     |     |  |  +--rw clock-type?          oc-ptp-types:clock-type-enumeration
     |     |  |  +--rw sdoid?               uint16
     |     |  |  +--rw network-transport?   oc-ptp-types:network-transport-enumeration
     |     |  |  +--rw unicast-multicast?   oc-ptp-types:unicast-multicast-enumeration
     |     |  |  +--rw domain-profile?      oc-ptp-types:domain-profile-enumeration
     |     |  |  +--rw udp6-scope?          uint8
     |     |  |  +--rw master-ip*           inet:ip-address
     |     |  +--ro state
     |     |     +--ro priority1?           uint8
     |     |     +--ro priority2?           uint8
     |     |     +--ro domain-number?       uint8
     |     |     +--ro slave-only?          boolean
     |     |     +--ro clock-type?          oc-ptp-types:clock-type-enumeration
     |     |     +--ro sdoid?               uint16
     |     |     +--ro network-transport?   oc-ptp-types:network-transport-enumeration
     |     |     +--ro unicast-multicast?   oc-ptp-types:unicast-multicast-enumeration
     |     |     +--ro domain-profile?      oc-ptp-types:domain-profile-enumeration
     |     |     +--ro udp6-scope?          uint8
     |     |     +--ro master-ip*           inet:ip-address
     |     |     +--ro two-step-flag?       boolean
     |     |     +--ro clock-identity?      oc-ptp-types:clock-identity-type
     |     |     +--ro number-ports?        uint16
     |     |     +--ro clock-quality
     |     |        +--ro clock-class?                  uint8
     |     |        +--ro clock-accuracy?               uint8
     |     |        +--ro offset-scaled-log-variance?   uint16
     |     +--rw port-datasets
     |     |  +--rw port-dataset* [port-number]
     |     |     +--rw port-number    -> ../config/port-number
     |     |     +--rw config
     |     |     |  +--rw port-number?                   uint16
     |     |     |  +--rw underlying-interface?          if:interface-ref
     |     |     |  +--rw log-announce-interval?         int8
     |     |     |  +--rw announce-receipt-timeout?      uint8
     |     |     |  +--rw log-sync-interval?             int8
     |     |     |  +--rw delay-mechanism?               oc-ptp-types:delay-mechanism-enumeration
     |     |     |  +--rw log-min-pdelay-req-interval?   int8
     |     |     |  +--rw version-number?                uint8
     |     |     |  +--rw unicast-multicast?             oc-ptp-types:unicast-multicast-enumeration
     |     |     +--ro state
     |     |        +--ro port-number?                   uint16
     |     |        +--ro underlying-interface?          if:interface-ref
     |     |        +--ro log-announce-interval?         int8
     |     |        +--ro announce-receipt-timeout?      uint8
     |     |        +--ro log-sync-interval?             int8
     |     |        +--ro delay-mechanism?               oc-ptp-types:delay-mechanism-enumeration
     |     |        +--ro log-min-pdelay-req-interval?   int8
     |     |        +--ro version-number?                uint8
     |     |        +--ro unicast-multicast?             oc-ptp-types:unicast-multicast-enumeration
     |     |        +--ro port-state?                    oc-ptp-types:port-state-enumeration
     |     |        +--ro log-min-delay-req-interval?    int8
     |     |        +--ro peer-mean-path-delay?          oc-ptp-types:time-interval-type
     |     +--rw parent-datasets
     |        +--rw parent-dataset* [parent-id]
     |           +--rw parent-id    -> ../config/parent-id
     |           +--rw config
     |           |  +--rw parent-id?   uint16
     |           +--ro state
     |              +--ro parent-id?                                    uint16
     |              +--ro parent-port-identity
     |              |  +--ro clock-identity?   oc-ptp-types:clock-identity-type
     |              |  +--ro port-number?      uint16
     |              +--ro parent-stats?                                 boolean
     |              +--ro observed-parent-offset-scaled-log-variance?   uint16
     |              +--ro observed-parent-clock-phase-change-rate?      int32
     |              +--ro grandmaster-identity?                         oc-ptp-types:clock-identity-type
     |              +--ro grandmaster-clock-quality
     |              |  +--ro clock-class?                  uint8
     |              |  +--ro clock-accuracy?               uint8
     |              |  +--ro offset-scaled-log-variance?   uint16
     |              +--ro grandmaster-priority1?                        uint8
     |              +--ro grandmaster-priority2?                        uint8
     +--rw transparent-clock
        +--rw default-dataset
        |  +--rw config
        |  |  +--rw delay-mechanism?   oc-ptp-types:delay-mechanism-enumeration
        |  |  +--rw primary-domain?    uint8
        |  |  +--rw two-step-flag?     boolean
        |  +--ro state
        |     +--ro clock-identity?    oc-ptp-types:clock-identity-type
        |     +--ro number-ports?      uint16
        |     +--ro delay-mechanism?   oc-ptp-types:delay-mechanism-enumeration
        |     +--ro primary-domain?    uint8
        |     +--ro two-step-flag?     boolean
        +--rw port-datasets
           +--rw port-dataset* [port-number]
              +--rw port-number    -> ../config/port-number
              +--rw config
              |  +--rw port-number?            uint16
              |  +--rw underlying-interface?   if:interface-ref
              |  +--rw network-transport?      oc-ptp-types:network-transport-enumeration
              +--ro state
                 +--ro port-number?                   uint16
                 +--ro underlying-interface?          if:interface-ref
                 +--ro network-transport?             oc-ptp-types:network-transport-enumeration
                 +--ro log-min-pdelay-req-interval?   int8
                 +--ro faulty-flag?                   boolean
                 +--ro peer-mean-path-delay?          oc-ptp-types:time-interval-type
```

### CODE REVIEW

**Comment by proberts2022** [comment]
I am new to this process of adding to the openconfig model but I hope review comments are welcomed.  I have many years working with PTP and when I look at this model that has been defined for PTP in openconfig, I see differences here compared to the datasets of the IEEE1588 standard itself and also with the draft YANG model as defined by the IEEE1588 working group. 
 
I think the model defined within openconfig should align with the datasets of the standard and avoid as much as possible additional attributes that may be implementation specific.

Here is a list of the items I saw that are different in this model compared to the standard:

Firstly, I am confused as to why the parent-dataset is defined as a list when an individual PTP clock instance can only have one single parent clock at any given time.  Within the IEEE1588 standard there is only one instance of a parentDS.  I think this level of list hierarchy should be removed.

Secondly, while the model does seem to include support for PTP over IP, it doesn’t include any support for the unicast discovery and unicast message negotiation.  Is the intention that only static IP is to be supported for now?

default-dataset:config:domain-profile 
– this is defining the profile in use by the clock.  I agree this is necessary and the method to set this is not well defined in the standard itself.
default-dataset:config:network-transport 
-	This seems to be indicating that the PTP clock shall only operate with one transport protocol.  This is not a restriction required by the standard itself.  In theory, a clock may use PTP over UDP/IPv4 communication with some external PTP clocks while using PTP over UDP/IPv6 with other PTP clocks.  The transport layer protocol should be defined for each port in the port-dataset and I believe this is via the configurable underlying-interface.  I think this leaf should be removed
default-dataset:config:unicast-multicast 
port-dataset:config:unicast-multicast
-	I support the concept of this configurable parameter at the port level, but I don’t agree with a global setting for the entire clock.  And what are the procedures when a port setting conflicts with the global clock setting.  I think the default-dataset leaf should be removed.
default-dataset:udp6-scope
-	This is not in the standard but does seem useful as is to apply to all UDP/IPv6 multicast messages generated out of this PTP clock, if that transport mode is used.
default-dataset:master-ip [list]
-	It is not clear to me what this list is defining.  Is this a list of IP used by PTP clocks external to this clock and if so how is this list to be used?  Is this the acceptable master table but using IP addresses?  Is it addresses t which this clock should send Signaling messages with Unicast Negotiation TLVs?

**Comment by SulabhMohanSharma** [comment]
Yang model is not inline with IEEE1588 yang model.
pls refer P1588e:
https://github.com/YangModels/yang/blob/main/standard/ieee/draft/1588/ieee1588-ptp-ms.yang
this is already approved and should be publish in few months.

**Comment by RodneyCummings** [comment]
I agree with @SulabhMohanSharma. This module is somewhat-aligned with the IEEE 1588 data sets, but not completely. In other standardization organizations, that sort of difference has proven to be quite painful for implementers. It is much safer to stick to the standard.

At a minimum, I think this PR should list the reasons for diverging from the IEEE 1588 standard.

Some possible reasons:

1. P1588e does not use sensitive terminology: There is a module to solve that:
https://github.com/YangModels/yang/blob/main/standard/ieee/draft/1588/ieee1588-ptp-tt.yang

2. OpenConfig needs to add its own nodes: This can be done by importing the P1588e module and augmenting its tree. ITU-T and IEEE 802.1 are doing this.

3. P1588e has too many nodes: All nodes are formally optional, so OpenConfig can specify a smaller subset as required in order for servers to provide a more compact model.

4. OpenConfig cannot wait: IEEE Std P1588e is past the balloting stage, with formal IEEE approval (i.e., RevCom) scheduled for Jan 29, so it is moving from "draft" to "published" very soon.

**Comment by kam-gopalakrishnan** [comment]
Let's not reinvent one more YANG data model for PTP. Let's use the IEEE1588e standardized data model here in openconfig.

**Comment by proberts2022** [comment]
I had a number of comments as well.  I noted them in Issue #1039  Can we discuss these as well.

**Comment by sallylsy** [comment]
I submitted a new PR based on our discussion. Please find the new model in https://github.com/openconfig/public/pull/1103

**Comment by dplore** [comment]
@proberts2022 @kam-gopalakrishnan please provide any comments so we can move this forward.

**Comment by proberts2022** [comment]
Its unclear where we should be adding comments.   Issue https://github.com/openconfig/public/issues/1039 , Pull request https://github.com/openconfig/public/pull/1036 or Pull Request https://github.com/openconfig/public/pull/1103

I added the following to 1103:
1 Configuration of unicast versus multicast?
default-dataset:config:unicast-multicast
port-dataset:config:unicast-multicast

If the network transport protocol and the unicast/multicast qualifier are to be applied at the default-ds level, why is the unicast-multicast leaf necessary within the portDS?

master-ip list?
default-dataset:config:master-ip [list]
"A list of IP addresses."
Can you please provide a more detailed description of the use of this list. It is not clear to me what this list is defining. Is this a list of IP used by PTP clocks external to this clock and if so how is this list to be used? Is this the acceptable master table but using IP addresses? Is it addresses to which this clock should send Signaling messages with Unicast Negotiation TLVs?

**Comment by dplore** [comment]
@sallylsy are you still pursuing this model update?

**Comment by dplore** [comment]
Obsoleted by https://github.com/openconfig/public/pull/1103

**Pull request closed without merging**
