### PR TITLE
Add IPv4 address type

### PR DESCRIPTION
**Pull request by rolandphung**
### Change Scope

* Add `type` to IPv4 address configuration to support PRIMARY and SECONDARY addressing for all L3 interfaces with IPv4 address support. There should only be one PRIMARY address per interface, while there could be multiple secondary IPs.
* This change is backwards compatible

### Platform Implementations

 * Arista [documentation](https://www.arista.com/en/um-eos/eos-data-plane-security#xx1144036)
   * `ip address <addr> secondary`

Relevant pyang output:
```
module: openconfig-interfaces
  +--rw interfaces
     +--rw interface* [name]
        +--rw subinterfaces
           +--rw subinterface* [index]
              +--rw oc-ip:ipv4
                 +--rw oc-ip:addresses
                    +--rw oc-ip:address* [ip]
                       +--rw oc-ip:ip        -> ../config/ip
                       +--rw oc-ip:config
                       |  +--rw oc-ip:ip?              oc-inet:ipv4-address
                       |  +--rw oc-ip:prefix-length?   uint8
                       |  +--rw oc-ip:type?            ipv4-address-type
                       +--ro oc-ip:state
                       |  +--ro oc-ip:ip?              oc-inet:ipv4-address
                       |  +--ro oc-ip:prefix-length?   uint8
                       |  +--ro oc-ip:type?            ipv4-address-type
                       |  +--ro oc-ip:origin?          ip-address-origin

module: openconfig-interfaces
  +--rw interfaces
     +--rw interface* [name]
        +--rw oc-vlan:routed-vlan
           +--rw oc-ip:ipv4
              +--rw oc-ip:addresses
                 +--rw oc-ip:address* [ip]
                    +--rw oc-ip:ip        -> ../config/ip
                    +--rw oc-ip:config
                    |  +--rw oc-ip:ip?              oc-inet:ipv4-address
                    |  +--rw oc-ip:prefix-length?   uint8
                    |  +--rw oc-ip:type?            ipv4-address-type
                    +--ro oc-ip:state
                    |  +--ro oc-ip:ip?              oc-inet:ipv4-address
                    |  +--ro oc-ip:prefix-length?   uint8
                    |  +--ro oc-ip:type?            ipv4-address-type
                    |  +--ro oc-ip:origin?          ip-address-origin

module: openconfig-interfaces
  +--rw interfaces
     +--rw interface* [name]
        +--rw oc-tun:tunnel
           +--rw oc-tun:ipv4
              +--rw oc-tun:addresses
                 +--rw oc-tun:address* [ip]
                    +--rw oc-tun:ip        -> ../config/ip
                    +--rw oc-tun:config
                    |  +--rw oc-tun:ip?              oc-inet:ipv4-address
                    |  +--rw oc-tun:prefix-length?   uint8
                    |  +--rw oc-tun:type?            ipv4-address-type
                    +--ro oc-tun:state
                       +--ro oc-tun:ip?              oc-inet:ipv4-address
                       +--ro oc-tun:prefix-length?   uint8
                       +--ro oc-tun:type?            ipv4-address-type
                       +--ro oc-tun:origin?          ip-address-origin
```

### CODE REVIEW

**Comment by missaesasaya** [comment]
This could be done also for the addresses under /oc-if:interfaces/oc-if:interface/oc-if:subinterfaces/oc-if:subinterface/oc-ip:ipv4/oc-ip:addresses/oc-ip:address.

**Comment by rolandphung** [comment]
> This could be done also for the addresses under /oc-if:interfaces/oc-if:interface/oc-if:subinterfaces/oc-if:subinterface/oc-ip:ipv4/oc-ip:addresses/oc-ip:address.

I forgot this applies to all L3 interfaces that uses this grouping. Let me update the pyang output.

**Comment by chrisy** [comment]
I don't have a major reservation over this change, but we've used the convention that the first address in the list is the primary, all others are secondary. This change does not break that assertion, but I do have a mild "is this necessary?" twinge, but not enough to make a fuss.

**Comment by dplore** [comment]
Seems like there should be an _explicit_ indication of which IP address should be used by a device to source packets when there is more than one IP address on an interface.    This setting is common across various implementations.  I am ok with it.  Setting last call for comments and will merge on May 24.

Additional implementations:

[Cisco XROS uses a 'secondary' keyword](https://www.cisco.com/c/en/us/td/docs/routers/xr12000/software/xr12k_r4-3/addr_serv/command/reference/b_ipaddr_cr43xr12k/b_ipaddr_cr42xr12k_chapter_01000.html#wp3476291820) when multiple IP addresses are configured

[JunOS uses preferred and primary keywords](https://www.juniper.net/documentation/us/en/software/junos/interfaces-ethernet-switches/topics/ref/statement/primary-edit-interfaces.html) when multiple IP addresses are configured

[Nokia SRLinux supports a primary keyword](https://documentation.nokia.com/cgi-bin/dbaccessfilename.cgi/3HE16819AAAATQZZA01_V1_SR%20Linux%20R21.3%20Configuration%20Basics.pdf) when multiple IP addresses are configured

**Review by dplore — CHANGES_REQUESTED** [review]
Can you fix the whitespace please, thanks!

**Pull request merged**
