### PR TITLE
Clarify disable-metric-propagation

### PR DESCRIPTION
**Pull request by dplore**
### Change Scope

* Specify setting metric to `0` for route redistribution when disable-metric-propagation is set to `true`.
* Previously the description said to use the 'default' metric or policy.  But it is not clear where the 'default' metric is defined.  

### Implementation References

* Example from [Cisco IOS XR](https://www.cisco.com/c/en/us/td/docs/routers/xr12000/software/xr12k_r3-9/routing/configuration/guide/xr12krc39_chapter2.html#task_1061883)
shows metric configuration (either through the default-metric command or a route policy) for redistribution of routes from BGP to EIGRP with a metric specified.  

* Example from [JunOS](https://www.juniper.net/documentation/us/en/software/junos/is-is/bgp/topics/example/isis-community-policy.html) shows metric configuration between BGP and ISIS.

### CODE REVIEW

**Review by s19nal — DISMISSED** [review]
LGTM

**Comment by dplore** [comment]
@s19nal I fixed the merge conflicts, can you re-review/approve?

**Comment by dplore** [comment]
Added references to 2 implementations demonstrating capability to configure a fixed metric for route redistribution.

**Review by s19nal — APPROVED** [review]
LGTM

**Pull request merged**
