### PR TITLE
Add description leaf for local-routing

### PR DESCRIPTION
**Pull request by exa-arrcus**

### CODE REVIEW

**Comment by exa-arrcus** [comment]
Simple addition of a description leaf for static/aggregate routes

```
module: openconfig-local-routing
  +--rw local-routes
     +--rw config
     +--ro state
     +--rw static-routes
     |  +--rw static* [prefix]
     |     +--rw prefix       -> ../config/prefix
     |     +--rw config
     |     |  +--rw prefix?        inet:ip-prefix
     |     |  +--rw set-tag?       oc-pt:tag-type
     |     |  +--rw description?   string
     |     +--ro state
     |     |  +--ro prefix?        inet:ip-prefix
     |     |  +--ro set-tag?       oc-pt:tag-type
     |     |  +--ro description?   string
     |     +--rw next-hops
     |        +--rw next-hop* [index]
     |           +--rw index            -> ../config/index
     |           +--rw config
     |           |  +--rw index?      string
     |           |  +--rw next-hop?   union
     |           |  +--rw metric?     uint32
     |           |  +--rw recurse?    boolean
     |           +--ro state
     |           |  +--ro index?      string
     |           |  +--ro next-hop?   union
     |           |  +--ro metric?     uint32
     |           |  +--ro recurse?    boolean
     |           +--rw interface-ref
     |              +--rw config
     |              |  +--rw interface?      -> /oc-if:interfaces/interface/name
     |              |  +--rw subinterface?   -> /oc-if:interfaces/interface[oc-if:name=current()/../interface]/subinterfaces/subinterface/index
     |              +--ro state
     |                 +--ro interface?      -> /oc-if:interfaces/interface/name
     |                 +--ro subinterface?   -> /oc-if:interfaces/interface[oc-if:name=current()/../interface]/subinterfaces/subinterface/index
     +--rw local-aggregates
        +--rw aggregate* [prefix]
           +--rw prefix    -> ../config/prefix
           +--rw config
           |  +--rw prefix?        inet:ip-prefix
           |  +--rw discard?       boolean
           |  +--rw set-tag?       oc-pt:tag-type
           |  +--rw description?   string
           +--ro state
              +--ro prefix?        inet:ip-prefix
              +--ro discard?       boolean
              +--ro set-tag?       oc-pt:tag-type
              +--ro description?   string
```

```
module: openconfig-network-instance
  +--rw network-instances
     +--rw network-instance* [name]
        +--rw protocols
           +--rw protocol* [identifier name]
              +--rw static-routes
                 +--rw static* [prefix]
                    +--rw prefix       -> ../config/prefix
                    +--rw config
                    |  +--rw prefix?        inet:ip-prefix
                    |  +--rw set-tag?       oc-pt:tag-type
                    |  +--rw description?   string
                    +--ro state
                    |  +--ro prefix?        inet:ip-prefix
                    |  +--ro set-tag?       oc-pt:tag-type
                    |  +--ro description?   string
                    +--rw next-hops
                       +--rw next-hop* [index]
                          +--rw index            -> ../config/index
                          +--rw config
                          |  +--rw index?      string
                          |  +--rw next-hop?   union
                          |  +--rw metric?     uint32
                          |  +--rw recurse?    boolean
                          +--ro state
                          |  +--ro index?      string
                          |  +--ro next-hop?   union
                          |  +--ro metric?     uint32
                          |  +--ro recurse?    boolean
                          +--rw interface-ref
                             +--rw config
                             |  +--rw interface?      -> /oc-if:interfaces/interface/name
                             |  +--rw subinterface?   -> /oc-if:interfaces/interface[oc-if:name=current()/../interface]/subinterfaces/subinterface/index
                             +--ro state
                                +--ro interface?      -> /oc-if:interfaces/interface/name
                                +--ro subinterface?   -> /oc-if:interfaces/interface[oc-if:name=current()/../interface]/subinterfaces/subinterface/index
```

```
module: openconfig-network-instance
  +--rw network-instances
     +--rw network-instance* [name]
        +--rw protocols
           +--rw protocol* [identifier name]
              +--rw local-aggregates
                 +--rw aggregate* [prefix]
                    +--rw prefix    -> ../config/prefix
                    +--rw config
                    |  +--rw prefix?        inet:ip-prefix
                    |  +--rw discard?       boolean
                    |  +--rw set-tag?       oc-pt:tag-type
                    |  +--rw description?   string
                    +--ro state
                       +--ro prefix?        inet:ip-prefix
                       +--ro discard?       boolean
                       +--ro set-tag?       oc-pt:tag-type
                       +--ro description?   string
```

**Comment by robshakir** [comment]
Hi @exa-arrcus 

Thanks for the change -- LGTM.

To document checking here:
* Supported in IOS XR as [`description`](https://www.cisco.com/c/en/us/td/docs/routers/xr12000/software/xr12k_r4-1/routing/configuration/guide/routing_cg41xr12k_chapter8.html)
* This doesn't look to be supported in [JUNOS](https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/static-edit-routing-options.html)
* EOS supports this with `ip route ... name`.
* I assume Arrcus supports this based on this PR.

I'll take this change and make it upstream.

Cheers,
r.

**Comment by exa-arrcus** [comment]
Thx @robshakir - yes we support this in ArcOS

Junos somewhat supports the notion by way of annotations `<junos:comment/>` that are related to other nodes (but not a direct schema tree node)

**Comment by robshakir** [comment]
Thanks for this change, it was merged in 0d5539927e42eac65db007885cf75c0a02b103be.

**Pull request closed without merging**
