### PR TITLE
Fix ygot CI

### PR DESCRIPTION
**Pull request by wenovus**

### CODE REVIEW

**Comment by robshakir** [comment]
Did this fix the CI at this point, Wen, or is there something more we should look at?

**Comment by robshakir** [comment]
Looks like this is fixed at this point, do you still want to submit this? (I couldn't tell whether the change of GCB base image was needed here or not.)

**Comment by wenovus** [comment]
> Looks like this is fixed at this point, do you still want to submit this? (I couldn't tell whether the change of GCB base image was needed here or not.)
No it's not fixed, the GCB trigger somehow got disconnected between yesterday and this morning. I just messaged you offline about this issue.

**Review by robshakir — APPROVED** [review]

**Comment by wenovus** [comment]
@robshakir @dplore ready to merge now.

**Pull request merged**
