### PR TITLE
Add SSID to neighbor-table

### PR DESCRIPTION
**Pull request by mike-albano**
*Add additional leaf to neighbors container for SSID name
*Up version to 0.1.1
*Fix spelling mistakes

LMK if preferable to open 'issue' prior to PR when syncing from private-->public.

### CODE REVIEW

**Comment by aashaikh** [comment]
Just suggest we try to use the (roughly) uniform format for the commit message (can see other recent commits to public repo).

**Comment by mike-albano** [comment]
Noted. This would be more like:
"""
Add SSID to neighbor-table for oc-wifi-phy:neighbor-list-state.
This commit adds an additional leaf to neighbors-list-state container for SSID name, as well as fixing spelling mistakes.
"""

**Comment by aashaikh** [comment]
We've generally done something more like:

```
Additions and fixes to wifi phy model.
    
      * (M) release/models/wifi/phy/openconfig-wifi-phy.yang
        - Added ssid leaf to neighbor state
        - Corrected typos
```

**Comment by mike-albano** [comment]
Got it, thanks.

**Pull request merged**
