### PR TITLE
Optical channel reference to it's logical channel

### PR DESCRIPTION
**Pull request by ejbrever**
New leafref added: `/components/component/optical-channel/state/logical-channel-assignment `

More details at:
https://github.com/openconfig/public/issues/1128

## Tree output
```
module: openconfig-platform
  +--rw components
     +--rw component* [name]
        +--rw name                           -> ../config/name
        <...>
        +--rw oc-opt-term:optical-channel
           +--rw oc-opt-term:config
           |  +--rw oc-opt-term:frequency?             oc-opt-types:frequency-type
           |  +--rw oc-opt-term:target-output-power?   decimal64
           |  +--rw oc-opt-term:operational-mode?      uint16
           |  +--rw oc-opt-term:line-port?             -> /oc-platform:components/component/name
           +--ro oc-opt-term:state
              +--ro oc-opt-term:frequency?                                   oc-opt-types:frequency-type
              +--ro oc-opt-term:target-output-power?                         decimal64
              +--ro oc-opt-term:operational-mode?                            uint16
              +--ro oc-opt-term:line-port?                                   -> /oc-platform:components/component/name
              +--ro oc-opt-term:group-id?                                    uint32
              +--ro oc-opt-term:logical-channel-assignment?                  -> /terminal-device/logical-channels/channel/index
              +--ro oc-opt-term:chromatic-dispersion
              +--ro oc-opt-term:polarization-mode-dispersion
              +--ro oc-opt-term:second-order-polarization-mode-dispersion
              +--ro oc-opt-term:polarization-dependent-loss
              +--ro oc-opt-term:modulator-bias-xi
              +--ro oc-opt-term:modulator-bias-xq
              +--ro oc-opt-term:modulator-bias-yi
              +--ro oc-opt-term:modulator-bias-yq
              +--ro oc-opt-term:modulator-bias-x-phase
              +--ro oc-opt-term:modulator-bias-y-phase
              +--ro oc-opt-term:osnr
              +--ro oc-opt-term:carrier-frequency-offset
              +--ro oc-opt-term:sop-roc
              +--ro oc-opt-term:modulation-error-ratio
              +--ro oc-opt-term:fec-uncorrectable-blocks?                    yang:counter64
              +--ro oc-opt-term:pre-fec-ber
              +--ro oc-opt-term:post-fec-ber
              +--ro oc-opt-term:q-value
              +--ro oc-opt-term:esnr
```

### CODE REVIEW

**Comment by ejbrever** [comment]
@ahsaanyousaf @dplore could you please help review? Thanks.

**Review by dplore — COMMENTED** [review]
This looks good to me from a model and use case perspective.  Is there any evidence of implementation of this mapping?

**Comment by ejbrever** [comment]
Unfortunately, I don't know of any vendor implementations that tried to do an augment for this. For an internal project (DCGate) there are performance concerns as the current leaf that maps logical channels to optical channels (i.e. opposite direction) you could have something that kind of starts to look like an N^2 problem (with hundreds of logical channels, each with a handful of logical-channel-assignments) because to find the logical channel that maps to a specific optical channel would require looping through every assignment. With this approach, it becomes a simple targeted lookup.

**Comment by ejbrever** [comment]
Hi Darren, as suggested, here is a pyang output showing the new 'logical-channel-assignment' leaf.

Please let me know if I can provide anything else. Thanks.

module: openconfig-platform
  +--rw components
     +--rw component* [name]
        +--rw name                           -> ../config/name
        <...>
        +--rw oc-opt-term:optical-channel
           +--rw oc-opt-term:config
           |  +--rw oc-opt-term:frequency?             oc-opt-types:frequency-type
           |  +--rw oc-opt-term:target-output-power?   decimal64
           |  +--rw oc-opt-term:operational-mode?      uint16
           |  +--rw oc-opt-term:line-port?             -> /oc-platform:components/component/name
           +--ro oc-opt-term:state
              +--ro oc-opt-term:frequency?                                   oc-opt-types:frequency-type
              +--ro oc-opt-term:target-output-power?                         decimal64
              +--ro oc-opt-term:operational-mode?                            uint16
              +--ro oc-opt-term:line-port?                                   -> /oc-platform:components/component/name
              +--ro oc-opt-term:group-id?                                    uint32
              +--ro oc-opt-term:logical-channel-assignment?                  -> /terminal-device/logical-channels/channel/index
              +--ro oc-opt-term:chromatic-dispersion
              +--ro oc-opt-term:polarization-mode-dispersion
              +--ro oc-opt-term:second-order-polarization-mode-dispersion
              +--ro oc-opt-term:polarization-dependent-loss
              +--ro oc-opt-term:modulator-bias-xi
              +--ro oc-opt-term:modulator-bias-xq
              +--ro oc-opt-term:modulator-bias-yi
              +--ro oc-opt-term:modulator-bias-yq
              +--ro oc-opt-term:modulator-bias-x-phase
              +--ro oc-opt-term:modulator-bias-y-phase
              +--ro oc-opt-term:osnr
              +--ro oc-opt-term:carrier-frequency-offset
              +--ro oc-opt-term:sop-roc
              +--ro oc-opt-term:modulation-error-ratio
              +--ro oc-opt-term:fec-uncorrectable-blocks?                    yang:counter64
              +--ro oc-opt-term:pre-fec-ber
              +--ro oc-opt-term:post-fec-ber
              +--ro oc-opt-term:q-value
              +--ro oc-opt-term:esnr

**Comment by dplore** [comment]
Last call for comments.  To be merged on July 29, 2024

**Review by dplore — APPROVED** [review]

**Pull request merged**
