### PR TITLE
Add BGP default import/export policy into global config

### PR DESCRIPTION
**Pull request by rolandphung**
### Change Scope
* The purpose of this change is to add a global level of default action for import/export policy. This configuration would be inherited by each neighbor/peer-group and the respective afi-safi.
* Add the following paths into .../bgp/global and .../bgp/global/afi-safis/afi-safi/
  * apply-policy/default-import-policy
  * apply-policy/default-export-policy
* Refactored apply-policy grouping to separate default from regular policy
  * Split `default-(import|export)-policy` leaves from `apply-policy-(import|export)-config` grouping
  * Created separate `default-policy-config` and `default-policy-group` grouping
    * `default-policy-config` houses `default-(import|export)-policy` groupings
    * `default-policy-group` contains the `config`/`state` containers with just the default policy leaves
  * Updated ISIS, BGP, OSPF, and table-connections groupings to use separate `default-policy-(import|export)-config` groupings
* This change is backwards compatible

#### Relevant pyang output:
```
module: openconfig-network-instance
  +--rw network-instances
     +--rw network-instance* [name]
        +--rw protocols
           +--rw protocol* [identifier name]
              +--rw bgp
                 +--rw global
                    +--rw apply-policy
                       +--rw config
                       |  +--rw default-import-policy?   default-policy-type
                       |  +--rw default-export-policy?   default-policy-type
                       +--ro state
                          +--ro default-import-policy?   default-policy-type
                          +--ro default-export-policy?   default-policy-type
module: openconfig-network-instance
  +--rw network-instances
     +--rw network-instance* [name]
        +--rw protocols
           +--rw protocol* [identifier name]
              +--rw bgp
                 +--rw global
                    +--rw afi-safis
                       +--rw afi-safi* [afi-safi-name]
                          +--rw apply-policy
                             +--rw config
                             |  +--rw default-import-policy?   default-policy-type
                             |  +--rw default-export-policy?   default-policy-type
                             +--ro state
                                +--ro default-import-policy?   default-policy-type
                                +--ro default-export-policy?   default-policy-type
```

### Platform Implementations

 * Arista: [link to documentation](https://www.arista.com/en/um-eos/eos-border-gateway-protocol-bgp#xx1117976)

### CODE REVIEW

**Comment by dplore** [comment]
Will review on Oct 17th OC Operators meeting

**Comment by dplore** [comment]
Reviewed in Oct 24th OC operators meeting.   Generally this looks like a good change.  

@rolandphung Can you update to fix the version bumps?   Also, can you note the additional containers which were updated in your description.  (Currently you mention bgp sections, but there are others (isis, ospf).  Are there any other areas that need to be updated?

**Comment by rolandphung** [comment]
> Reviewed in Oct 24th OC operators meeting. Generally this looks like a good change.
> 
> @rolandphung Can you update to fix the version bumps? Also, can you note the additional containers which were updated in your description. (Currently you mention bgp sections, but there are others (isis, ospf). Are there any other areas that need to be updated?

Updated the version and date to today. I've also updated the description as requested. I've done a scan across all usage of these leaves/groupings that were touched and there are no other places that are affected by this refactor.

**Review by dplore — APPROVED** [review]

**Comment by dplore** [comment]
[JunOS Default routing policy](https://www.juniper.net/documentation/us/en/software/junos/routing-policy/topics/concept/policy-routing-policies-actions-defaults.html)

[Cisco IOS XR policy-global](https://www.cisco.com/c/en/us/td/docs/routers/xr12000/software/xr12k_r4-0/routing/configuration/guide/rc40xr12k_chapter7.html#con_1238028)

**Pull request merged**
